[package]
name = "tidy-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
tinyset = "0.4.10"

[dev-dependencies]
rand = "0.8.5"

